# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20160306_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rookie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
