# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20160306_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
