# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='gps',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
