# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20160306_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursetype',
            new_name='type',
        ),
    ]
