# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20160306_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('coverage', models.DateTimeField(blank=True, null=True)),
                ('green', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('submission', models.CharField(blank=True, max_length=10, null=True)),
                ('grid', models.CharField(blank=True, max_length=150, null=True)),
                ('rowsize', models.IntegerField(default=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Course')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Start')),
            ],
            options={
                'db_table': 'race',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Race')),
            ],
            options={
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'resulttype',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ResultType'),
        ),
    ]
