# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20160306_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='race',
        ),
        migrations.AddField(
            model_name='result',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Course'),
        ),
    ]
