# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_result_races'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='result',
            table='result',
        ),
    ]
