# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20160306_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='races',
            field=models.ManyToManyField(related_name='results', to='manager.Race'),
        ),
    ]
