# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20160306_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='races',
        ),
        migrations.AddField(
            model_name='result',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Race'),
        ),
    ]
