# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20160307_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('submission', models.CharField(blank=True, max_length=10, null=True)),
                ('publish_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['last', 'first']},
        ),
    ]
