# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20160313_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
