# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20160320_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.RedditAccount'),
            preserve_default=False,
        ),
    ]
