# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20160320_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credit',
            field=models.BooleanField(default=True),
        ),
    ]
