# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_post_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='endcoverage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='practice',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
