# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20160330_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='urlpostrace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='urlpractice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='urlrace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
