# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20160330_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
