# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_driver_died'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='urlrr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
