# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_race_urlrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='leadchanges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='speedavg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='speedpole',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='yellowflags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='yellowlaps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
