# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_auto_20160501_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='fanfav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_fanfav', to='manager.Driver'),
        ),
        migrations.AddField(
            model_name='season',
            name='rookie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_rookie', to='manager.Driver'),
        ),
    ]
