# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_season_champion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
                ('startLap', models.IntegerField()),
                ('endLap', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Race')),
            ],
            options={
                'ordering': ['race'],
                'db_table': 'caution',
            },
        ),
        migrations.CreateModel(
            name='CautionDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Caution')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Driver')),
            ],
            options={
                'ordering': ['caution'],
                'db_table': 'caution_driver',
            },
        ),
    ]
