# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_caution_cautiondriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CautionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['reason'],
                'db_table': 'caution_reason',
            },
        ),
        migrations.AddField(
            model_name='caution',
            name='desc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
