# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_auto_20160509_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautionreason',
            name='reason',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
