# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_auto_20160509_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caution',
            old_name='desc',
            new_name='description',
        ),
    ]
