# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_auto_20160509_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caution',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.CautionReason'),
        ),
    ]
