# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_sessiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('posttime', models.DateTimeField(blank=True, null=True)),
                ('post', models.BooleanField(default=False)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Race')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.SessionType')),
            ],
        ),
    ]
