# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
