# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
    ]
