# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_tweet_tweeted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweeted',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
