# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_tweet_deleted'),
        ('manager', '0044_auto_20160608_1703'),
    ]

    operations = [
    ]
