# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_auto_20160614_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Post'),
        ),
        migrations.AlterField(
            model_name='session',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Channel'),
        ),
    ]
