# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_auto_20160622_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stream',
            field=models.BooleanField(default=False),
        ),
    ]
