# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_post_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flair_css_class',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='flair_text',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
