# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_auto_20160624_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
