# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_post_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
