# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_course_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='headerimgurl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
