# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-05 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_keyvaluestore'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyvaluestore',
            table='keyvaluestore',
        ),
    ]
