# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-05 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_auto_20170605_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyValueStore',
        ),
    ]
